name: 'Action skipper'
description: 'Used to skip actions when there are no important files and previos run succeeded.'
branding:
  icon: 'file'
  color: 'blue'
inputs:
  increment-section:
    description: 'Version section to increment. Possible values: major, minor, patch'
    required: true
    default: 'patch'
  snapshot:
    description: 'In the next version should be a snapshot version'
    required: true
    default: 'false'
  manual-version:
    description: 'Manually specified next version that should be validated'
    required: false
    default: ''
outputs:
  version:
    description: 'Current version'
    value: ${{ steps.version.outputs.version }}
  next_version:
    description: 'Next version'
    value: ${{ steps.version.outputs.next_version }}
runs:
  using: "composite"
  steps:
    - id: skipper
      shell: bash
      env:
        INCREMENT_SECTION: ${{ inputs.increment-section }}
        SNAPSHOT: ${{ inputs.snapshot }}
        MANUAL_VERSION: ${{ inputs.manual-version }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      run: $GITHUB_ACTION_PATH/action.sh
